#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later

set -euo pipefail

PROJECT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
cd "$PROJECT_DIR"

DEVICE=""
PREPARE_ONLY=false

usage() {
  echo "Usage: ./build.sh [--prepare-only | --device <device>]"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --prepare-only)
      PREPARE_ONLY=true
      shift
      ;;
    --device)
      if [[ $# -lt 2 || -z $2 ]]; then
        echo "--device requires a device name, hostname or serial port" >&2
        usage >&2
        exit 2
      fi
      DEVICE="$2"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ $PREPARE_ONLY == true && -n $DEVICE ]]; then
  echo "--prepare-only cannot be combined with --device" >&2
  usage >&2
  exit 2
fi

VERSION="$(git describe --tags --always --dirty)"
if [[ ! $VERSION =~ ^[[:alnum:]._-]+$ ]]; then
  echo "Unsupported character in firmware version: $VERSION" >&2
  exit 1
fi

SOURCE_FILE="web/powermanager.js"
GENERATED_FILE="web/powermanager.generated.js"
MARKER='const firmwareVersion = "development (not built)";'

if [[ $(grep -Fxc "$MARKER" "$SOURCE_FILE") -ne 1 ]]; then
  echo "Expected exactly one firmware version marker" >&2
  exit 1
fi

{
  echo '// Generated by build.sh; edit powermanager.js instead.'
  sed "s|^${MARKER}$|const firmwareVersion = \"${VERSION}\";|" "$SOURCE_FILE"
} > "$GENERATED_FILE"

tools/embed-logo.sh
echo "Firmware version: $VERSION"

if [[ $PREPARE_ONLY == false ]]; then
  venv/bin/esphome compile powermanager.yaml
fi

if [[ -n $DEVICE ]]; then
  venv/bin/esphome upload powermanager.yaml --device "$DEVICE"
fi
